# SPDX-FileCopyrightText: Simon Schneegans <code@simonschneegans.de>
# SPDX-License-Identifier: CC0-1.0

name: Checks

on:
  push:
    branches:
      - '**'

jobs:
  reuse:
    name: Check Compliance with REUSE Specification
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: REUSE Compliance Check
        uses: fsfe/reuse-action@v1

  eslint:
    name: Check ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Dependencies
        run: |
          sudo apt install libx11-dev
          npm ci
      - name: Run ESLint
        run: npm run lint

  prettier:
    name: Check Prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Dependencies
        run: |
          sudo apt install libx11-dev
          npm ci
      - name: Run Prettier
        run: npm run prettier
